# Generated by Django 5.1.3 on 2024-11-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_outline',
            field=models.CharField(max_length=1000),
        ),
    ]
