# Generated by Django 5.1.3 on 2024-11-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_course_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='number_of_questions',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
