# Generated by Django 5.1.3 on 2024-11-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_remove_exam_number_of_questions_alter_exam_exam_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_text',
            new_name='exam_questions',
        ),
    ]
