# Generated by Django 5.1.3 on 2024-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_remove_course_uploaded_file_course_university_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='course',
            name='university_logo',
            field=models.ImageField(blank=True, upload_to='university_logos/'),
        ),
    ]
